Update goodtermbadterm

diff --git a/goodtermbadterm b/goodtermbadterm
--- a/goodtermbadterm
+++ b/goodtermbadterm
@@ -1,27 +1,16 @@
-#using this within .bashrc to generate 
-#color codes in terminal prompt per exit stats of last command
-
+#Add to .bash_profile or .bashrc
+#Creates color-scheme per exit code in prompt
 
 PROMPT_COMMAND=__prompt_command # Func to gen PS1 after CMDs
 
 __prompt_command() {
-    local EXIT="$?"             # This needs to be first
+    local EXIT="$?"                                # This needs to be first
     PS1=""
-
-    #local RCol='\[\e[0m\]'
-
-    #local Red='\[\e[0;31m\]'
-    #local Gre='\[\e[0;32m\]'
-    #local BYel='\[\e[1;33m\]'
-    #local BBlu='\[\e[1;34m\]'
-    #local Pur='\[\e[0;35m\]'
     NO_FORMAT="\033[0m"
     G_FOR="\033[38;5;27m"
     G_BAK="\033[48;5;83m"
-
     B_FOR="\033[38;5;86m"
     B_BAK="\033[48;5;9m"
-
 
     if [ $EXIT != 0 ]; then
         PS1+="${B_FOR}${B_BAK}\u${NO_FORMAT}"      # Add red if exit code non 0
@@ -31,5 +20,5 @@ __prompt_command() {
         SYM="+"
     fi
 
-    PS1+="${NO_FORMAT}${SYM}\h\W${NO_FORMAT}"
+    PS1+="${NO_FORMAT}${SYM}\h=>\W${NO_FORMAT}  "
 }
